In [1]:
import requests
import json
import urllib
import matplotlib.pyplot as plt
import numpy as np
from pandas import DataFrame as pd

In [2]:
ip = "localhost" #"192.168.0.114"
port = "5001"
query = "http://{}:{}/health".format(ip, port)
r = requests.get(query)
json.loads(r.text)

{'success': True}

In [3]:
query = "http://{}:{}/getDistinct".format(ip, port)
r = requests.get(query)
inp = json.loads(r.text)
dist = pd.from_dict(inp)
dist

    symbol
0     MSFT
1      SPX
10     AMD
100    CNC
101    CNP
102    CTL
103   CERN
104     CF
105   SCHW
106   CHTR
107    CVX
108    CMG
109     CB
11     AAP
110    CHD
111     CI
112    XEC
113   CINF
114   CTAS
115   CSCO
116      C
117    CFG
118   CTXS
119    CLX
12     AES
120    CME
121    CMS
122     KO
123   CTSH
124     CL
..     ...
72   BRK.B
73     BBY
74    BIIB
75     BLK
76     HRB
77      BA
78    BKNG
79     BWA
8     ATVI
80     BXP
81     BSX
82     BHF
83     BMY
84    AVGO
85      BR
86    CHRW
87     COG
88    CDNS
89     CPB
9     ADBE
90     COF
91     CAH
92     KMX
93     CCL
94     CAT
95    CBOE
96    CBRE
97     CBS
98      CE
99    CELG

[505 rows x 1 columns]

In [4]:
query = "http://{}:{}/getStock/MSFT".format(ip, port)
r = requests.get(query)
inp = json.loads(r.text)
df = pd.from_dict(inp)
df = df.sort_values(by='date')
df

,adjusted_close,close,date,dividend_amount,high,id,low,open,split_coefficient,symbol,volume
5474,10.6408,131.13,1998-01-02,0.0,131.5000,MSFT1998-01-02,129.5000,129.6300,1.0,MSFT,4968500
5473,10.5799,130.38,1998-01-05,0.0,133.6300,MSFT1998-01-05,127.8700,131.2500,1.0,MSFT,10047200
5472,10.6408,131.13,1998-01-06,0.0,133.0000,MSFT1998-01-06,129.2500,129.7500,1.0,MSFT,8479300
5471,10.5134,129.56,1998-01-07,0.0,131.1900,MSFT1998-01-07,127.5000,129.8800,1.0,MSFT,7686600
5470,10.5897,130.50,1998-01-08,0.0,132.1300,MSFT1998-01-08,127.5000,128.6300,1.0,MSFT,9702400
5469,10.3057,127.00,1998-01-09,0.0,131.5000,MSFT1998-01-09,125.8700,130.0600,1.0,MSFT,10941800
5468,10.5085,129.50,1998-01-12,0.0,130.0000,MSFT1998-01-12,124.3700,124.6200,1.0,MSFT,9799200
5467,10.7220,132.13,1998-01-13,0.0,132.2500,MSFT1998-01-13,128.1300,129.5000,1.0,MSFT,8368200
5466,10.6408,131.13,1998-01-14,0.0,132.5000,MSFT1998-01-14,129.2500,132.1300,1.0,MSFT,6846800
5465,10.7366,132.31,1998-01-15,0.0,133.0000,MSFT1998-01-15,129.8800,130.3800,1.0,MSFT,6327800
5464,10.9751,135.25,1998-01-16,0.0,135.3800,MSFT1998-01-16,132.3100,132.3800,1.0,MSFT,9117900
5463,11.1829,137.81,1998-01-20,0.0,138.0000,MSFT1998-01-20,134.0000,134.1300,1.0,MSFT,8119500
5462,11.1171,137.00,1998-01-21,0.0,138.4400,MSFT1998-01-21,135.6300,137.2500,1.0,MSFT,10695900
5461,11.2494,138.63,1998-01-22,0.0,139.8800,MSFT1998-01-22,135.3100,135.5600,1.0,MSFT,19892400
5460,11.2186,138.25,1998-01-23,0.0,139.4400,MSFT1998-01-23,136.7000,138.7500,1.0,MSFT,7914000
5459,11.5026,141.75,1998-01-26,0.0,141.8800,MSFT1998-01-26,138.4500,139.8800,1.0,MSFT,9284700
5458,11.7817,145.19,1998-01-27,0.0,145.8800,MSFT1998-01-27,141.5600,142.3800,1.0,MSFT,12192600
5457,12.0909,149.00,1998-01-28,0.0,149.5000,MSFT1998-01-28,145.5000,146.2500,1.0,MSFT,9923400
5456,12.0300,148.25,1998-01-29,0.0,150.1300,MSFT1998-01-29,147.5000,148.9400,1.0,MSFT,9196400
5455,12.1063,149.19,1998-01-30,0.0,150.0000,MSFT1998-01-30,147.6300,148.6300,1.0,MSFT,6258900
5454,12.5680,154.88,1998-02-02,0.0,155.1300,MSFT1998-02-02,150.5000,151.7500,1.0,MSFT,12299700
5453,12.6492,155.88,1998-02-03,0.0,156.1300,MSFT1998-02-03,153.8100,155.1300,1.0,MSFT,7671800
5452,12.7247,156.81,1998-02-04,0.0,158.0000,MSFT1998-02-04,155.0600,155.8800,1.0,MSFT,7742600
5451,12.6135,155.44,1998-02-05,0.0,158.7500,MSFT1998-02-05,154.7500,158.1300,1.0,MSFT,8376800
5450,12.8318,158.13,1998-02-06,0.0,158.2500,MSFT1998-02-06,155.1300,155.3800,1.0,MSFT,6258800
5449,12.7555,157.19,1998-02-09,0.0,158.8800,MSFT1998-02-09,155.6300,158.7500,1.0,MSFT,6835200
5448,12.9227,159.25,1998-02-10,0.0,159.5000,MSFT1998-02-10,156.7500,157.2500,1.0,MSFT,6012400
5447,12.8975,158.94,1998-02-11,0.0,160.0600,MSFT1998-02-11,157.0600,159.3800,1.0,MSFT,9557500
5446,12.8821,158.75,1998-02-12,0.0,158.9400,MSFT1998-02-12,156.4400,158.0600,1.0,MSFT,9582300
5445,12.7807,157.50,1998-02-13,0.0,158.7500,MSFT1998-02-13,157.3800,158.6300,1.0,MSFT,5275400
...,...,...,...,...,...,...,...,...,...,...,...
29,133.3900,133.39,2019-08-23,0.0,138.3500,MSFT2019-08-23,132.8000,137.1897,1.0,MSFT,32523998
28,135.4500,135.45,2019-08-26,0.0,135.5600,MSFT2019-08-26,133.9125,134.9900,1.0,MSFT,16560059
27,135.7400,135.74,2019-08-27,0.0,136.7200,MSFT2019-08-27,134.6681,134.9900,1.0,MSFT,16639726
26,135.5600,135.56,2019-08-28,0.0,135.7600,MSFT2019-08-28,133.5500,134.8800,1.0,MSFT,16321151
25,138.1200,138.12,2019-08-29,0.0,138.4400,MSFT2019-08-29,136.9100,134.8800,1.0,MSFT,18547744
24,137.8600,137.86,2019-08-30,0.0,139.1000,MSFT2019-08-30,136.2800,134.8800,1.0,MSFT,21877723
23,136.0400,136.04,2019-09-03,0.0,137.2000,MSFT2019-09-03,135.7000,136.6100,1.0,MSFT,18869300
22,137.6300,137.63,2019-09-04,0.0,137.6900,MSFT2019-09-04,136.4800,137.3000,1.0,MSFT,17995900
21,140.0500,140.05,2019-09-05,0.0,140.3837,MSFT2019-09-05,138.7700,139.1100,1.0,MSFT,22667945
20,139.1000,139.10,2019-09-06,0.0,140.1600,MSFT2019-09-06,138.2000,140.0300,1.0,MSFT,17737384
19,137.5200,137.52,2019-09-09,0.0,139.7500,MSFT2019-09-09,136.4600,139.5900,1.0,MSFT,25108693
18,136.0800,136.08,2019-09-10,0.0,136.8862,MSFT2019-09-10,134.5100,136.8000,1.0,MSFT,23811204
17,136.1200,136.12,2019-09-11,0.0,136.2700,MSFT2019-09-11,135.0900,135.9100,1.0,MSFT,19614590
16,137.5200,137.52,2019-09-12,0.0,138.4200,MSFT2019-09-12,136.8700,137.8500,1.0,MSFT,24854822
15,137.3200,137.32,2019-09-13,0.0,138.0600,MSFT2019-09-13,136.5700,137.7800,1.0,MSFT,16554185
14,136.3300,136.33,2019-09-16,0.0,136.7000,MSFT2019-09-16,135.6600,135.8300,1.0,MSFT,14785072
13,137.3900,137.39,2019-09-17,0.0,137.5200,MSFT2019-09-17,136.4250,136.9600,1.0,MSFT,13585841
12,138.5200,138.52,2019-09-18,0.0,138.6700,MSFT2019-09-18,136.5299,137.3600,1.0,MSFT,18980208
11,141.0700,141.07,2019-09-19,0.0,142.3700,MSFT2019-09-19,140.0798,140.3000,1.0,MSFT,32444985
10,139.4400,139.44,2019-09-20,0.0,141.6500,MSFT2019-09-20,138.2500,141.0100,1.0,MSFT,32979846
9,139.1400,139.14,2019-09-23,0.0,139.6300,MSFT2019-09-23,138.4400,139.2300,1.0,MSFT,17139300
8,137.3800,137.38,2019-09-24,0.0,140.6900,MSFT2019-09-24,136.8850,140.3600,1.0,MSFT,24602078
7,139.3600,139.36,2019-09-25,0.0,139.9580,MSFT2019-09-25,136.0400,137.5000,1.0,MSFT,20835063
6,139.5400,139.54,2019-09-26,0.0,140.1800,MSFT2019-09-26,138.4400,139.4400,1.0,MSFT,14538002
5,137.7300,137.73,2019-09-27,0.0,140.3600,MSFT2019-09-27,136.6500,140.1500,1.0,MSFT,22477700
4,139.0300,139.03,2019-09-30,0.0,139.2150,MSFT2019-09-30,137.7900,138.0500,1.0,MSFT,12533517
3,137.0700,137.07,2019-10-01,0.0,140.2500,MSFT2019-10-01,137.0000,139.6600,1.0,MSFT,17489944
2,134.6500,134.65,2019-10-02,0.0,136.3700,MSFT2019-10-02,133.5799,136.2500,1.0,MSFT,29232922
1,136.2800,136.28,2019-10-03,0.0,136.7500,MSFT2019-10-03,133.2200,134.9500,1.0,MSFT,21462874
0,138.1200,138.12,2019-10-04,0.0,138.2500,MSFT2019-10-04,136.4200,136.7500,1.0,MSFT,17807467

In [228]:
# Target value - i days into the future
i = 2
target = (df["adjusted_close"].shift(-i) - df["adjusted_close"]) / df["adjusted_close"]

In [ ]:
# from sklearn.base import BaseEstimator, ClassifierMixin

# class stockTransformer(BaseEstimator, ClassifierMixin):
#     def __init__(self):
#         pass

#     def fit(self, X, y=None):
#         return self

#     def _meaning(self, x):
#         return(True)

#     def transform(self, tmp, y=None):
#         #Vi tittar tillbaka {i} dagar
#         for j in [1,2,3,5,7,10]: #range(1, 10):
#             for c in ["adjusted_close", "high", "low", "open", "volume"]: #"close", 
#                 tmp["hist_{}_{}".format(c,j)] = (tmp[c].shift(j) - tmp[c]) / tmp[c]

#         # Date -> month / day
#         tmp["month"] = tmp["date"].apply(lambda x : x.split("-")[1])
#         tmp["day"] = tmp["date"].apply(lambda x : x.split("-")[2])

#         tmp = tmp.drop(["adjusted_close", "close", "date", "dividend_amount", "high", "id", "low", "open", "split_coefficient", "symbol", "volume"], axis=1)
#         return tmp.fillna(-1)  # TODO - ta bort NaN frÃ¥n bÃ¥de X/Y
        
#     def predict(self, X, y=None):
#         return(X)

#     def score(self, X, y=None):
#         return(sum(self.predict(X)))

In [237]:
from pandas import Timestamp
t = Timestamp("1999-02-02")
str(t).split("-")
# st = stockTransformer()
# tmp = st.transform(df)[:2]

['1999', '02', '02 00:00:00']

In [255]:
import pandas
# df.date = df.date.astype(str)
# df.info()

# df.date.map(lambda x: x.split("-"))
# df.date.astype()
tmp = df.to_json()
j = pandas.read_json(tmp)
j.date = j.date.astype(str)
j.head().date.map(lambda x: str(x).split("-"))

0       [2019, 07, 12]
1       [2019, 07, 11]
10      [2019, 06, 27]
100     [2019, 02, 19]
1000    [2015, 07, 22]
Name: date, dtype: object

In [5]:
import requests

url = "http://127.0.0.1:5002/invocations"
data = df[:2]
headers = {
    'Content-Type': 'application/json; format=pandas-split',
}

response = requests.post(url, headers=headers, data=data.to_json(orient='split'))
response.text
# data.to_json()
# data

'[[0.4, 0.6], [0.8, 0.2]]'

In [186]:
#
# Wine test
#

import pandas as pd 

wine_path = "/home/hades/program/python/jupyter/stock19/wine-quality.csv"
data = pd.read_csv(wine_path)

url = "http://127.0.0.1:5003/invocations"
data = data[:2] #.to_json()

headers = {
    'Content-Type': 'application/json; format=pandas-split',
}


# d2 = '{"columns":["alcohol", "chlorides", "citric acid", "density", "fixed acidity", "free sulfur dioxide", "pH", "residual sugar", "sulphates", "total sulfur dioxide", "volatile acidity"],"data":[[12.8, 0.029, 0.48, 0.98, 6.2, 29, 3.33, 1.2, 0.39, 75, 0.66]]}'

response = requests.post('http://127.0.0.1:5003/invocations', headers=headers, data=data.drop(columns=['quality']).to_json(orient='split'))
response.text

# print(d)
# print()
# print(str(d2))
# data.to_json()
# data.drop(columns=['quality']).to_json()

'[5.655099099229193, 5.630318463109261]'